site_name: Data Science @ SDG
site_url: https://example.com/
site_description: >-
  Information for the DS group.

repo_name: DSdocs
repo_url: https://github.com/pietro-nobili-SDG/dsdocs
edit_uri: blob/main/docs

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      # primary: blue
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate # attach arbitrary content to specific sections of code
    - content.tabs.link     # all content tabs across the whole documentation site will be linked and switch to the same label when the user clicks on a tab
    - navigation.instant    # clicks on all internal links will be intercepted and dispatched without fully reloading the page
    # - navigation.tabs     # top-level sections are rendered in a menu layer below the header
    # - navigation.tracking # URL in the address bar is automatically updated with the active anchor
    # - navigation.expand   # left sidebar will expand all collapsible subsections by default
    - navigation.indexes    # documents can be directly attached to sections
    - navigation.top        # back-to-top button shown when the user starts to scroll up again
    - toc.follow            # sidebar is automatically scrolled so that the active anchor is always visible
    - search.suggest        # search will display the likeliest completion for the last word, accept with Right key

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Setup: setup/env.md
  - ML: 
    - NLP:
      - Hugging Face: machine_learning/nlp/huggingface.md
      - SpaCy: machine_learning/nlp/spacy.md
    - Time Series:
      - machine_learning/time_series/index.md
      - SkTime: machine_learning/time_series/sktime.md
  - Tools: 
    - tools/index.md
    - Databricks: 
      - Scheduling: tools/databricks/scheduling.md
      - Notebook: tools/databricks/notebook.md
    - MLFlow: tools/MLFlow/jobs.md
    - LogicApp: tools/logicapp/scheduling.md
  - General:
    - Command-line interface: general/cli.md
    - Git: general/git.md
    - Mk Docs: mkdocs/guide.md
  - Contributing: mkdocs/contributing.md
  - About: about.md
  - License: license.md
